spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kirana_db
    username: meenakshirajesh
    password: JAR@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


